version: "1"
module_version: 0.0.52
runner_image: spacelift/runner:latest

tests:
  - name: Simple Usage
    project_root: examples/simple-usage

  - name: Stack with Env Vars
    project_root: examples/stack-with-env-vars

  - name: Stack with Env Vars (TF 0.15)
    project_root: examples/stack-with-env-vars
    terraform_version: 1.8.3
